name: DORA Metrics Tracking
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, closed]
  issues:
    types: [opened, closed, labeled]
  workflow_dispatch:

jobs:
  calculate-dora-metrics:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Calculate Deployment Frequency
        run: |
          echo "=== DEPLOYMENT FREQUENCY ==="
          DEPLOYMENTS_30_DAYS=$(gh api repos/${{ github.repository }}/actions/workflows/deploy.yml/runs \
            --jq '[.workflow_runs[] | select(.created_at > (now - 30*24*3600 | strftime("%Y-%m-%dT%H:%M:%SZ")))] | length')
          echo "Deployments in last 30 days: $DEPLOYMENTS_30_DAYS"
          echo "Deployment frequency: $(echo "scale=2; $DEPLOYMENTS_30_DAYS / 4.3" | bc) per week"
          
      - name: Calculate Lead Time for Changes
        if: github.event.pull_request.merged == true
        run: |
          echo "=== LEAD TIME FOR CHANGES ==="
          PR_CREATED="${{ github.event.pull_request.created_at }}"
          PR_MERGED="${{ github.event.pull_request.merged_at }}"
          CREATED_SECONDS=$(date -d "$PR_CREATED" +%s)
          MERGED_SECONDS=$(date -d "$PR_MERGED" +%s)
          LEAD_TIME_HOURS=$(( ($MERGED_SECONDS - $CREATED_SECONDS) / 3600 ))
          echo "PR #${{ github.event.pull_request.number }} lead time: $LEAD_TIME_HOURS hours"
          
      - name: Calculate Change Failure Rate
        run: |
          echo "=== CHANGE FAILURE RATE ==="
          TOTAL_RUNS=$(gh api repos/${{ github.repository }}/actions/workflows/deploy.yml/runs --jq '.total_count')
          FAILED_RUNS=$(gh api repos/${{ github.repository }}/actions/workflows/deploy.yml/runs \
            --jq '[.workflow_runs[] | select(.conclusion == "failure")] | length')
          if [ "$TOTAL_RUNS" -gt 0 ]; then
            FAILURE_RATE=$(echo "scale=2; $FAILED_RUNS * 100 / $TOTAL_RUNS" | bc)
            echo "Total runs: $TOTAL_RUNS"
            echo "Failed runs: $FAILED_RUNS"
            echo "Change failure rate: $FAILURE_RATE%"
          fi
          
      - name: Calculate Mean Time to Recovery
        if: github.event.issue.labels[*].name contains 'incident' && github.event.action == 'closed'
        run: |
          echo "=== MEAN TIME TO RECOVERY ==="
          ISSUE_CREATED="${{ github.event.issue.created_at }}"
          ISSUE_CLOSED=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          CREATED_SECONDS=$(date -d "$ISSUE_CREATED" +%s)
          CLOSED_SECONDS=$(date -d "$ISSUE_CLOSED" +%s)
          RECOVERY_TIME_HOURS=$(( ($CLOSED_SECONDS - $CREATED_SECONDS) / 3600 ))
          echo "Incident #${{ github.event.issue.number }} recovery time: $RECOVERY_TIME_HOURS hours"
          
      - name: Store Metrics
        run: |
          echo "=== DORA METRICS SUMMARY ==="
          echo "Repository: ${{ github.repository }}"
          echo "Timestamp: $(date -u)"
          echo "Event: ${{ github.event_name }}"
          echo "Metrics calculated and logged above"
